---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url:
sections:
- type: heading
  label: team
- type: directory
  path: content/english/team
  label: Team (en)
  create: all
  match: "**/*"
  templates:
  - team
- type: heading
  label: Howitworks
- type: directory
  path: reddirtmentoringeducentre/content/english/howitworks
  label: Howitworks (en)
  create: all
  match: "**/*"
  templates:
  - howitworks
- type: heading
  label: Others Pages
- type: directory
  path: reddirtmentoringeducentre/content/english/about
  label: About (en)
  create: none
  match: "*"
- type: directory
  path: reddirtmentoringeducentre/content/english/contact
  label: Contact (en)
  create: none
  match: "*"
- type: directory
  path: reddirtmentoringeducentre/content/english/pages
  label: Created Pages (en)
  create: documents
  match: "**/*"
  templates:
  - new-page
- type: directory
  path: reddirtmentoringeducentre/content/english
  label: All Pages (en)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: directory
  path: reddirtmentoringeducentre/content/french
  label: All Pages (fr)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: heading
  label: Data
- type: directory
  path: reddirtmentoringeducentre/data/en
  label: Data (en)
  create: all
  match: "**/*"
- type: directory
  path: reddirtmentoringeducentre/data/fr
  label: Data (fr)
  create: all
  match: "**/*"
- type: directory
  path: reddirtmentoringeducentre/i18n
  label: i18n
  create: documents
  match: "**/*"
- type: heading
  label: Configuration
- type: directory
  path: reddirtmentoringeducentre
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: reddirtmentoringeducentre/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
